services:
  auth-service:
    build:
      context: ./auth-service
    image: pyms-auth-service:local
    ports:
      - "9001:9001"
    environment:
      JWT_SECRET: "supersecret"
      ACCESS_TOKEN_EXPIRE_MINUTES: "60"
      # JSON plegado para evitar errores de comillas en Windows
      USERS_JSON: >-
        [{"user":"admin","password":"Admin#123","role":"security_admin"},
         {"user":"viewer","password":"Viewer#123","role":"viewer"}]

  resource-api:
    build:
      context: ./resource-api
    image: pyms-resource-api:local
    ports:
      - "9002:9002"
    environment:
      JWT_SECRET: "supersecret"
      ALLOWED_ORIGINS: "*"
