apiVersion: v1
kind: Service
metadata:
  name: web-portal
  namespace: medisupply
spec:
  type: ClusterIP
  selector:
    app: web-portal
  ports:
    - name: http
      port: 80
      targetPort: 80
