apiVersion: batch/v1
kind: Job
metadata:
  name: reports-service-init-db
  namespace: medisupply
  labels: { app: reports-service, job: init-db }
spec:
  backoffLimit: 2
  template:
    metadata: { labels: { app: reports-service, job: init-db } }
    spec:
      restartPolicy: Never
      imagePullSecrets: [ { name: ecr-cred } ]
      containers:
        - name: init
          # image will be replaced by pipeline
          image: REPLACED_BY_PIPELINE
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          # Run init scripts; do not swallow errors so CI can detect failures
          args: ["python init_db.py; python scripts/ensure_jan2025.py"]
          env:
            - name: DB_HOST
              value: "postgres.medisupply.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom: { secretKeyRef: { name: postgres-secret, key: POSTGRES_DB } }
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: postgres-secret, key: POSTGRES_USER } }
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: postgres-secret, key: POSTGRES_PASSWORD } }
            - name: DATABASE_URL
              value: "postgresql+psycopg2://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
          envFrom:
            - configMapRef: { name: medisupply-config }
