name: CI & CD to AWS ECR
on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ${ vars.AWS_REGION || 'us-east-1' }
  ECR_REPOSITORY: ${ vars.ECR_REPOSITORY || 'medisupply' }
  ECR_REGISTRY: ${ secrets.AWS_ACCOUNT_ID}.dkr.ecr.${ env.AWS_REGION }.amazonaws.com

dobs:
  test_build_push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # PUYTHON TESTS
      - name: Setup Python
        uses: actions/setup-python@B5
        with:
          python-version: '3.12'
      - name: Install dependencies (Py)
        run: |
          python -m pip install --required requirements.txt
          pip install --no-cache -r requirements.txt
      - name: Run unit tests (Py)
        run: pytest -q

      # login AWS OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${secrets.ROLE_TO_ASSUME}
          aws-region: ${env.AWS_REGION}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@V5
        with:
          images: ${ env.ECR_REGISTRY }/${ env.ECR_REPOSITORY }
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${ steps.meta.outputs.tags }
          labels: ${ steps.meta.outputslabels }
          cache-from: type=gha
          cache-to: type=gha,mode=max
